import{a as c,S as d,i as l}from"./assets/vendor-c8cb2b96.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();c.defaults.headers.common["x-api-key"]="live_01CpbqxeCWY46DHHkvTE4IhORXHj0paah5YXqyDCzDLU1W8OHLbF5tQAW3KUzWio";c.defaults.baseURL="https://api.thecatapi.com/v1";function u(){return c.get("/breeds").then(o=>o.data)}function m(o){return c.get(`/images/search?breed_ids=${o}`).then(e=>e.data[0])}const s={select:document.querySelector(".breed-select"),container:document.querySelector(".container-select"),loader:document.querySelector(".loader"),errorText:document.querySelector(".error"),cardInfo:document.querySelector(".cat-info")},h=new d({select:s.select,data:[]});u().then(o=>{h.setData(f(o)),s.container.classList.remove("hidden")}).catch(o=>{console.log(o.message),l.show({title:"❌",message:"Oops! Something went wrong! Try reloading the page!",close:!1,timeout:0,theme:"light",color:"#b35c5c",position:"center",progressBarColor:"#50ac86"})}).finally(()=>{s.loader.classList.add("hidden")});function f(o){const e=o.map(({id:a,name:n})=>({value:a,text:n}));return e.unshift({placeholder:!0,text:"Choose a cat breed"}),e}function p(o){s.loader.classList.remove("hidden"),s.cardInfo.innerHTML="",o.target.value!=="Choose a cat breed"&&m(s.select.value).then(e=>{s.cardInfo.innerHTML=g(e)}).catch(e=>{console.log(e.message),l.show({title:"❌",message:"Oops! Something went wrong! Try reloading the page!",messageSize:"48px",close:!1,timeout:0,theme:"light",color:"#b35c5c",position:"center",progressBarColor:"#50ac86"})}).finally(()=>{s.loader.classList.add("hidden")})}function g({url:o,breeds:e}){return`
        <div class="picture-thumb" >
            <img class="picture" src="${o}" alt=""${e[0].alt_names} width="500">
        </div>
        <div class="container-info">
            <h1 class="title">${e[0].name}</h1>
            <p class="text">${e[0].description}</p>
            <h3 class="second-title">Temperament:</h3>
            <p class="text"> ${e[0].temperament}</p>
        </div>
    `}s.select.addEventListener("change",p);
//# sourceMappingURL=commonHelpers.js.map
