import{a as i,S as d,i as l}from"./assets/vendor-c8cb2b96.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function c(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerpolicy&&(o.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?o.credentials="include":r.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=c(r);fetch(r.href,o)}})();i.defaults.headers.common["x-api-key"]="live_01CpbqxeCWY46DHHkvTE4IhORXHj0paah5YXqyDCzDLU1W8OHLbF5tQAW3KUzWio";i.defaults.baseURL="https://api.thecatapi.com/v1";function u(){return i.get("/breeds").then(t=>{if(t.status!==200)throw new Error("Ohh, something wrong");return t.data})}function h(t){return i.get(`/images/search?breed_ids=${t}`).then(e=>{if(e.status!==200)throw new Error("Ohh, something wrong");return e.data[0]})}const n={select:document.querySelector(".breed-select"),container:document.querySelector(".container-select"),loader:document.querySelector(".loader"),errorText:document.querySelector(".error"),cardInfo:document.querySelector(".cat-info")},m=new d({select:n.select,data:[]});u().then(t=>{m.setData(f(t)),n.container.classList.remove("hidden")}).catch(t=>{console.log(t.message),l.show({title:"❌",message:"Oops! Something went wrong! Try reloading the page!",close:!1,timeout:0,theme:"light",color:"#b35c5c",position:"center",progressBarColor:"#50ac86"})}).finally(()=>{n.loader.classList.add("hidden")});function f(t){const e=t.map(({id:c,name:s})=>({value:c,text:s}));return e.unshift({placeholder:!0,text:"Choose a cat breed"}),e}function p(t){n.loader.classList.remove("hidden"),n.cardInfo.innerHTML="",t.target.value!=="Choose a cat breed"&&h(n.select.value).then(e=>{n.cardInfo.innerHTML=g(e)}).catch(e=>{console.log(e.message),l.show({title:"❌",message:"Oops! Something went wrong! Try reloading the page!",messageSize:"48px",close:!1,timeout:0,theme:"light",color:"#b35c5c",position:"center",progressBarColor:"#50ac86"})}).finally(()=>{n.loader.classList.add("hidden")})}function g({url:t,breeds:e}){return`
        <div class="picture-thumb" >
            <img class="picture" src="${t}" alt=""${e[0].alt_names} width="500">
        </div>
        <div class="container-info">
            <h1 class="title">${e[0].name}</h1>
            <p class="text">${e[0].description}</p>
            <h3 class="second-title">Temperament:</h3>
            <p class="text"> ${e[0].temperament}</p>
        </div>
    `}n.select.addEventListener("change",p);
//# sourceMappingURL=commonHelpers.js.map
